name: TicketScannerApp

options:
  bundleIdPrefix: com.noahbravefoundation
  deploymentTarget:
    iOS: "17.0"
  generateEmptyDirectories: true

packages:
  TicketScannerKit:
    path: ..

schemes:
  TicketScannerApp:
    build:
      targets:
        TicketScannerApp: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  TicketScannerApp:
    type: application
    platform: iOS
    sources:
      - TicketScannerApp
    resources:
      - TicketScannerApp/Assets.xcassets
    info:
      path: TicketScannerApp/Resources/Info.plist
      properties:
        CFBundleDisplayName: Ticket Scanner
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        CFBundleURLTypes:
          - CFBundleURLName: com.noahbravefoundation.ticketscannerapp
            CFBundleURLSchemes:
              - ticketscanner
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIRequiredDeviceCapabilities:
          - arm64
    dependencies:
      - package: TicketScannerKit
        product: TicketScannerKit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.noahbravefoundation.ticketscannerapp
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: TicketScannerApp/Resources/TicketScannerApp.entitlements
        SWIFT_VERSION: "6.0"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
